// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/app/profile": {
    params: {};
  };
  "/app/leaderboard": {
    params: {};
  };
  "/app/last-words": {
    params: {};
  };
  "/app/admin": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/app/profile" | "/app/leaderboard" | "/app/last-words" | "/app/admin";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "../components/Layout.tsx": {
    id: "../components/Layout";
    page: "/app/profile" | "/app/leaderboard";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/app/profile";
  };
  "routes/leaderboard.tsx": {
    id: "routes/leaderboard";
    page: "/app/leaderboard";
  };
  "routes/last-words.tsx": {
    id: "routes/last-words";
    page: "/app/last-words";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/app/admin";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/./routes/home.tsx");
  "../components/Layout": unknown;
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/leaderboard": typeof import("./app/routes/leaderboard.tsx");
  "routes/last-words": typeof import("./app/routes/last-words.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
};